# This file was generated by GoReleaser. DO NOT EDIT.
cask "wo" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "32737d89d0f044ebdfdbd071c41df0bf7bd3cea8c1316c436ed117e83f421cda"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c033c384deadddb4d07951725a6612fed2acfb35c2c9ebd72c6e53ad49c2d16"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6cd17a09f1a1fd7dacfe19812769a1b68249eca3cb5d6a3f9d167b7c5a14273"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ef7d35e4dd01f50319ab3a6994b9b82044debd4d12c0913ad2cb8cd1f319559"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wo"
  desc "Track what you're working on from the command line, with toggl track"
  homepage "https://github.com/fmeinhold/working-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wo"
  bash_completion "completions/wo.bash"
  fish_completion "completions/wo.fish"
  zsh_completion "completions/wo.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `wo init` to set up your toggl track API token and config.
    `wo skill --install` adds the Claude Code skill for driving it.
  EOS
end
