# This file was generated by GoReleaser. DO NOT EDIT.
cask "wo" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4e115bc97b48de0bb30ade76b18c371770a090a4a21379d566c302f5dd78af09"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84f27adadbe2409f337c087878782e7132ffd296e90d14463cc4f86b1560ab94"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12fb4e7b9062d047896bc565d786a8c3b78d7cb3540e951ea942f6e76914a0d1"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b58635ce5588954b0e284903c3bae21151561d9a3f22f40b9de605e9dd708d3"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wo"
  desc "Track what you're working on from the command line, with toggl track"
  homepage "https://github.com/fmeinhold/working-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wo"
  bash_completion "completions/wo.bash"
  fish_completion "completions/wo.fish"
  zsh_completion "completions/wo.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `wo init` to set up your toggl track API token and config.
    `wo skill --install` adds the Claude Code skill for driving it.
  EOS
end
