# This file was generated by GoReleaser. DO NOT EDIT.
cask "wo" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "d74fdcf95e303ee9d4854dd80797e01a397d99b7d850fbb515621dc72a884f3a"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9bd8873748dab0ad7eb9d5d954c8641683c61cfd3b14791960c836b5f23fc23"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d919f1b0b2d0b41f8b2381f9b81ebccae84880d439245810521a2d0ff695019f"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef14f011e8f1de80b7f31022bd4685dc0b1c6d7d886add742f57eb69632826c9"
      url "https://github.com/fmeinhold/working-on/releases/download/v#{version}/wo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wo"
  desc "Track what you're working on from the command line, with toggl track"
  homepage "https://github.com/fmeinhold/working-on"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `wo init` to set up your toggl track API token and config.
  EOS
end
